export const ACTIVE_CONTROL_MODULES = Object.freeze([
  {"id":"gravity-anchor","name":"Gravity Anchor","description":"Zieht Gegner in ein Zentrum.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Energy"},{"value":1,"id":"Control"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-gravity-anchor" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"energy","activationCost":30,"cooldown":12},
  {"id":"shock-net","name":"Shock Net","description":"Verbindet Gegner mit verlangsamenden Blitzen.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Charge"},{"value":1,"id":"Arc"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-shock-net" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"kill-charge","activationCost":8,"cooldown":12},
  {"id":"mine-wall","name":"Mine Wall","description":"Legt lineare Minensperre.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Cooldown"},{"value":1,"id":"Mine"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-mine-wall" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"cooldown","activationCost":0,"cooldown":12},
  {"id":"decoy-drone","name":"Decoy Drone","description":"Zieht Gegneraggro.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Energy"},{"value":1,"id":"Drone"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-decoy-drone" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"energy","activationCost":30,"cooldown":12},
  {"id":"repulsion-wave","name":"Repulsion Wave","description":"Stößt Gegner und Projektile weg.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Heat"},{"value":1,"id":"Nova"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-repulsion-wave" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"heat","activationCost":18,"cooldown":12},
  {"id":"void-tether","name":"Void Tether","description":"Bindet Elite an Position.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Void"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-void-tether" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"corruption","activationCost":8,"cooldown":12},
  {"id":"chronolock","name":"Chronolock","description":"Friert einen Zielbereich ein.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Cooldown"},{"value":1,"id":"Control"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-chronolock" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"cooldown","activationCost":0,"cooldown":12},
  {"id":"target-scramble","name":"Target Scramble","description":"Gegner greifen kurz einander an.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Charge"},{"value":1,"id":"Anomaly"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-target-scramble" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"kill-charge","activationCost":8,"cooldown":12},
  {"id":"nanite-snare","name":"Nanite Snare","description":"Infizierte Gegner werden verlangsamt.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Summon"},{"value":1,"id":"Control"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-nanite-snare" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"cooldown","activationCost":0,"cooldown":12},
  {"id":"orbit-cage","name":"Orbit Cage","description":"Klingen bilden stationären Käfig.","slot":"active","energyCost":13,"tags":[{"value":1,"id":"Energy"},{"value":1,"id":"Orbit"},{"value":1,"id":"ActiveModule"}],"effects":[{ "id": "module-orbit-cage" }],"affixPool":"utility","faultProfileId":"standard","unlockSource":"challenge","resourceModel":"energy","activationCost":30,"cooldown":12}
]);

