export const CORRUPTED_MODULES = Object.freeze([
  {"id":"black-heart","name":"Black Heart","description":"Große Energie, stetige Korruption.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Energy"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-black-heart" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-black-heart-positive","negativeEffect":"module-black-heart-negative"},
  {"id":"whispering-targeter","name":"Whispering Targeter","description":"Enormer Crit-Bonus, gelegentlich falsches Ziel.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Targeting"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-whispering-targeter" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-whispering-targeter-positive","negativeEffect":"module-whispering-targeter-negative"},
  {"id":"parasitic-cooling","name":"Parasitic Cooling","description":"Kühlt durch Verbrauch von Beschwörungen.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Cooling"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-parasitic-cooling" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-parasitic-cooling-positive","negativeEffect":"module-parasitic-cooling-negative"},
  {"id":"inverted-shield","name":"Inverted Shield","description":"Absorbiert Schaden und gibt ihn später zurück.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Shield"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-inverted-shield" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-inverted-shield-positive","negativeEffect":"module-inverted-shield-negative"},
  {"id":"hungry-socket","name":"Hungry Socket","description":"Verstärkt Chip durch Verbrauch eines Affixes.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Socket"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-hungry-socket" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-hungry-socket-positive","negativeEffect":"module-hungry-socket-negative"},
  {"id":"broken-timer","name":"Broken Timer","description":"Cooldown kann sofort oder doppelt lang sein.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Cooldown"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-broken-timer" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-broken-timer-positive","negativeEffect":"module-broken-timer-negative"},
  {"id":"friendly-fire-core","name":"Friendly Fire Core","description":"Massiver Explosionsbonus mit Eigengefährdung.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Explosive"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-friendly-fire-core" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-friendly-fire-core-positive","negativeEffect":"module-friendly-fire-core-negative"},
  {"id":"orphan-command","name":"Orphan Command","description":"Drohnen werden stärker und zeitweise feindlich.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Drone"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-orphan-command" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-orphan-command-positive","negativeEffect":"module-orphan-command-negative"},
  {"id":"mirror-wound","name":"Mirror Wound","description":"Kopiert Treffer auf Spieler und Gegner.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Echo"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-mirror-wound" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-mirror-wound-positive","negativeEffect":"module-mirror-wound-negative"},
  {"id":"unwritten-rule","name":"Unwritten Rule","description":"Ändert pro Sektor eine Kernregel.","slot":"passive","energyCost":18,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"Anomaly"},{"value":1,"id":"PassiveModule"}],"effects":[{ "id": "module-unwritten-rule" }],"affixPool":"corrupted","faultProfileId":"standard","unlockSource":"blueprint","corruption":8,"positiveEffect":"module-unwritten-rule-positive","negativeEffect":"module-unwritten-rule-negative"}
]);

