export const DEFENSIVE_PASSIVE_MODULES = Object.freeze([
  {"id":"phase-shield","name":"Phase Shield","description":"Ausweichen erzeugt kurz einen Schild.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Shield"},{"value":1,"id":"Dodge"},{"value":1,"id":"PassiveModule"}],"effects":["module-phase-shield"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"reactive-armor","name":"Reactive Armor","description":"Nach einem Treffer kurzzeitig Schadensreduktion.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Hull"},{"value":1,"id":"PassiveModule"}],"effects":["module-reactive-armor"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"nanite-repair","name":"Nanite Repair","description":"Heilt außerhalb unmittelbarer Gefahr.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Healing"},{"value":1,"id":"PassiveModule"}],"effects":["module-nanite-repair"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"emergency-cooling","name":"Emergency Cooling","description":"Bei 90 Hitze einmalig starke Kühlung.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Cooling"},{"value":1,"id":"PassiveModule"}],"effects":["module-emergency-cooling"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"damage-router","name":"Damage Router","description":"Ein Teil des Schadens verbraucht Energie.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Energy"},{"value":1,"id":"PassiveModule"}],"effects":["module-damage-router"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"last-barrier","name":"Last Barrier","description":"Bei kritischer Hull einmal pro Sektor Barriere.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Shield"},{"value":1,"id":"PassiveModule"}],"effects":["module-last-barrier"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"kinetic-dampers","name":"Kinetic Dampers","description":"Reduziert Rückstoß und Kontaktschaden.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Control"},{"value":1,"id":"PassiveModule"}],"effects":["module-kinetic-dampers"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"void-insulation","name":"Void Insulation","description":"Reduziert Korruptionsschaden, senkt Reinigung.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"PassiveModule"}],"effects":["module-void-insulation"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"drone-screen","name":"Drone Screen","description":"Drohnen können Projektile abfangen.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Drone"},{"value":1,"id":"Shield"},{"value":1,"id":"PassiveModule"}],"effects":["module-drone-screen"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"thermal-plating","name":"Thermal Plating","description":"Hohe Hitze gewährt Rüstung.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Heat"},{"value":1,"id":"Hull"},{"value":1,"id":"PassiveModule"}],"effects":["module-thermal-plating"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"blood-seal","name":"Blood Seal","description":"Überheilung wird Schild, erzeugt Korruption.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Healing"},{"value":1,"id":"Corruption"},{"value":1,"id":"PassiveModule"}],"effects":["module-blood-seal"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"mirror-shell","name":"Mirror Shell","description":"Gelegentliche Projektilreflexion.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Shield"},{"value":1,"id":"Echo"},{"value":1,"id":"PassiveModule"}],"effects":["module-mirror-shell"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"stasis-gel","name":"Stasis Gel","description":"Treffer verlangsamt Gegner in kleinem Radius.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Cooldown"},{"value":1,"id":"PassiveModule"}],"effects":["module-stasis-gel"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"ablative-lattice","name":"Ablative Lattice","description":"Verbraucht eine Modulstabilitätsschicht statt Hull.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Hull"},{"value":1,"id":"Sacrifice"},{"value":1,"id":"PassiveModule"}],"effects":["module-ablative-lattice"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"guardian-node","name":"Guardian Node","description":"Beschwört defensive Wächterdrohne.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Summon"},{"value":1,"id":"Shield"},{"value":1,"id":"PassiveModule"}],"effects":["module-guardian-node"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"fault-grounding","name":"Fault Grounding","description":"Leichte Fehler werden absorbiert.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Stability"},{"value":1,"id":"PassiveModule"}],"effects":["module-fault-grounding"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"cold-blood-loop","name":"Cold Blood Loop","description":"Kühlung heilt bei niedriger Hitze.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Cooling"},{"value":1,"id":"Healing"},{"value":1,"id":"PassiveModule"}],"effects":["module-cold-blood-loop"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"shock-absorber","name":"Shock Absorber","description":"Schockeffekte laden Schild.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Arc"},{"value":1,"id":"Shield"},{"value":1,"id":"PassiveModule"}],"effects":["module-shock-absorber"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"escape-vector","name":"Escape Vector","description":"Niedrige Hull reduziert Dodge-Cooldown.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Dodge"},{"value":1,"id":"PassiveModule"}],"effects":["module-escape-vector"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"},
  {"id":"phoenix-array","name":"Phoenix Array","description":"Einmalige Wiederbelebung mit maximaler Hitze.","slot":"passive","energyCost":11,"tags":[{"value":1,"id":"Revive"},{"value":1,"id":"Heat"},{"value":1,"id":"PassiveModule"}],"effects":["module-phoenix-array"],"affixPool":"defensive","faultProfileId":"standard","unlockSource":"research"}
]);

