export const UTILITY_MODULES = Object.freeze([
  {"id":"gravity-siphon","name":"Gravity Siphon","description":"Vergrößert Pickup-Radius und zieht leichte Gegner.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Pickup"},{"value":1,"id":"Control"},{"value":1,"id":"PassiveModule"}],"effects":["module-gravity-siphon"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"target-priority-core","name":"Target Priority Core","description":"Konfigurierbare Zielprioritäten.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Targeting"},{"value":1,"id":"PassiveModule"}],"effects":["module-target-priority-core"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"salvage-scanner","name":"Salvage Scanner","description":"Zeigt Prototyp- und Blaupausenchancen.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Loot"},{"value":1,"id":"PassiveModule"}],"effects":["module-salvage-scanner"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"affix-booster","name":"Affix Booster","description":"Verstärkt ein zufälliges Affix pro Sektor.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Affix"},{"value":1,"id":"PassiveModule"}],"effects":["module-affix-booster"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"motion-battery","name":"Motion Battery","description":"Bewegung erzeugt Energie.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Movement"},{"value":1,"id":"Energy"},{"value":1,"id":"PassiveModule"}],"effects":["module-motion-battery"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"extraction-beacon","name":"Extraction Beacon","description":"Erlaubt seltene Notextraktion.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Extraction"},{"value":1,"id":"PassiveModule"}],"effects":["module-extraction-beacon"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"flux-condenser","name":"Flux Condenser","description":"Mehr Flux, geringere Heilungsdrops.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Currency"},{"value":1,"id":"PassiveModule"}],"effects":["module-flux-condenser"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"map-probe","name":"Map Probe","description":"Deckt einen zusätzlichen Kartenknoten auf.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Navigation"},{"value":1,"id":"PassiveModule"}],"effects":["module-map-probe"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"workshop-pass","name":"Workshop Pass","description":"Eine zusätzliche Werkstattaktion.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Crafting"},{"value":1,"id":"PassiveModule"}],"effects":["module-workshop-pass"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"merchant-transponder","name":"Merchant Transponder","description":"Verbessert Händlerangebot.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Merchant"},{"value":1,"id":"PassiveModule"}],"effects":["module-merchant-transponder"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"heat-telemetry","name":"Heat Telemetry","description":"Zeigt nächste Überhitzungsquelle.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Heat"},{"value":1,"id":"PassiveModule"}],"effects":["module-heat-telemetry"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"fault-predictor","name":"Fault Predictor","description":"Zeigt Fehlerklasse früher.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Fault"},{"value":1,"id":"PassiveModule"}],"effects":["module-fault-predictor"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"corruption-filter","name":"Corruption Filter","description":"Verringert kleine Korruptionsbuchungen.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Corruption"},{"value":1,"id":"PassiveModule"}],"effects":["module-corruption-filter"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"module-switcher","name":"Module Switcher","description":"Ein passiver Slot im Sektor wechselbar.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Loadout"},{"value":1,"id":"PassiveModule"}],"effects":["module-module-switcher"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"socket-extractor","name":"Socket Extractor","description":"Erlaubt sichere Chip-Entnahme.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Socket"},{"value":1,"id":"PassiveModule"}],"effects":["module-socket-extractor"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"prototype-locker","name":"Prototype Locker","description":"Ein zusätzlicher markierter Prototyp.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Prototype"},{"value":1,"id":"PassiveModule"}],"effects":["module-prototype-locker"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"scrap-compactor","name":"Scrap Compactor","description":"Verkaufserlös steigt.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Currency"},{"value":1,"id":"PassiveModule"}],"effects":["module-scrap-compactor"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"elite-tracker","name":"Elite Tracker","description":"Markiert Elite-Spawns und Belohnungen.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Elite"},{"value":1,"id":"PassiveModule"}],"effects":["module-elite-tracker"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"coolant-reservoir","name":"Coolant Reservoir","description":"Speichert aktive Sofortkühlung.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Cooling"},{"value":1,"id":"PassiveModule"}],"effects":["module-coolant-reservoir"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"},
  {"id":"signal-decoder","name":"Signal Decoder","description":"Unbekannte Signaturen zeigen eine Zusatzinformation.","slot":"utility","energyCost":8,"tags":[{"value":1,"id":"Codex"},{"value":1,"id":"PassiveModule"}],"effects":["module-signal-decoder"],"affixPool":"utility","faultProfileId":"standard","unlockSource":"research"}
]);

