import { ASSEMBLY_EVENTS } from "../assembly-events.js";
import { assertAssemblyInvariants, getBranchNodeIds, getChildren, wouldCreateCycle } from "./assembly-graph.js";
import { createAssemblySnapshot } from "./assembly-snapshot.js";

export function createAssemblyService({ state, eventBus, idFactory, runInventory } = {}) {
  const getSnapshot = () => createAssemblySnapshot(state);
  const requireNode = nodeId => { const node = state.nodesById[nodeId]; if (!node) throw new Error(`Unknown assembly node: ${nodeId}`); return node; };
  const publish = (eventName, payload, { structural = true, visual = true } = {}) => { if (structural) state.structuralRevision += 1; if (visual) state.visualRevision += 1; assertAssemblyInvariants(state); if (eventName !== ASSEMBLY_EVENTS.CHANGED) eventBus?.emit(eventName, payload); eventBus?.emit(ASSEMBLY_EVENTS.CHANGED, getSnapshot()); };
  const publishDamageChange = nodeId => publish(ASSEMBLY_EVENTS.DAMAGE_CHANGED, { nodeId }, { structural: false, visual: true });

  function mountModule({ moduleInstanceId, definitionId, parentPort, assemblyProfile, transform }) { if (Object.values(state.nodesById).some(node => node.moduleInstanceId === moduleInstanceId)) throw new Error(`Module already mounted: ${moduleInstanceId}`); if (!parentPort || parentPort.occupiedByNodeId) throw new Error("Mount port is unavailable"); const nodeId = idFactory.create("assembly-node"); const node = { nodeId, parentNodeId: parentPort.parentNodeId, parentPortId: parentPort.portId, moduleInstanceId, definitionId, visualProfileId: assemblyProfile.visualProfileId, variantSeed: assemblyProfile.variantSeed, sizeClass: assemblyProfile.sizeClass, mountType: parentPort.mountType, mass: assemblyProfile.mass, localPosition: transform.position, localRotation: transform.rotation, armorIntegrity: assemblyProfile.damage.armor, maxArmorIntegrity: assemblyProfile.damage.armor, coreIntegrity: assemblyProfile.damage.core, maxCoreIntegrity: assemblyProfile.damage.core, damageState: "intact", childPortIds: [] }; state.nodesById[nodeId] = node; state.portsById[parentPort.portId] = { ...parentPort, occupiedByNodeId: nodeId }; const connectionId = idFactory.create("assembly-connection"); state.connectionsById[connectionId] = { connectionId, sourceNodeId: parentPort.parentNodeId, targetNodeId: nodeId, sourcePortId: parentPort.portId, structuralStrength: parentPort.loadCapacity, energyThroughput: parentPort.energyClass, visualConnectorType: parentPort.mountType }; for (const template of assemblyProfile.childPorts ?? []) { const portId = idFactory.create("assembly-port"); state.portsById[portId] = { ...template, portId, parentNodeId: nodeId, branchDepth: (parentPort.branchDepth ?? 0) + 1, occupiedByNodeId: null }; node.childPortIds.push(portId); } publish(ASSEMBLY_EVENTS.MODULE_MOUNTED, { nodeId, moduleInstanceId }); return nodeId; }
  function moveNode({ nodeId, targetPort, transform }) { const node = requireNode(nodeId); if (nodeId === state.rootNodeId) throw new Error("Node cannot be moved"); if (!targetPort || targetPort.occupiedByNodeId) throw new Error("Target port is unavailable"); if (wouldCreateCycle(state, nodeId, targetPort.parentNodeId)) throw new Error("Move would create a cycle"); const oldPort = state.portsById[node.parentPortId]; if (oldPort) state.portsById[oldPort.portId] = { ...oldPort, occupiedByNodeId: null }; state.portsById[targetPort.portId] = { ...targetPort, occupiedByNodeId: nodeId }; Object.assign(node, { parentNodeId: targetPort.parentNodeId, parentPortId: targetPort.portId, localPosition: transform.position, localRotation: transform.rotation }); const connection = Object.values(state.connectionsById).find(item => item.targetNodeId === nodeId); if (connection) Object.assign(connection, { sourceNodeId: targetPort.parentNodeId, sourcePortId: targetPort.portId }); publish(ASSEMBLY_EVENTS.MODULE_MOVED, { nodeId, targetPortId: targetPort.portId }); return nodeId; }
  function addSecondaryConnection({ sourceNodeId, targetNodeId, profile }) { requireNode(sourceNodeId); requireNode(targetNodeId); const connectionId = idFactory.create("assembly-bridge"); state.secondaryConnectionsById[connectionId] = { connectionId, sourceNodeId, targetNodeId, structuralStrength: profile.structuralStrength, energyThroughput: profile.energyThroughput, visualConnectorType: profile.visualConnectorType }; publish(ASSEMBLY_EVENTS.CHANGED, { connectionId }); return connectionId; }
  function detachNode({ nodeId, detachBranch = false }) { if (nodeId === state.rootNodeId) throw new Error("Root node cannot be detached"); if (!detachBranch && getChildren(state, nodeId).length) throw new Error("Node has dependent children"); const rootParentPortId = requireNode(nodeId).parentPortId; const nodeIds = detachBranch ? getBranchNodeIds(state, nodeId) : [nodeId]; for (const currentId of [...nodeIds].reverse()) { const node = requireNode(currentId); state.detachedItems.push({ moduleInstanceId: node.moduleInstanceId, definitionId: node.definitionId, formerNodeId: currentId, damageState: "detached" }); for (const portId of node.childPortIds ?? []) delete state.portsById[portId]; delete state.nodesById[currentId]; for (const [id, connection] of Object.entries(state.connectionsById)) if (connection.sourceNodeId === currentId || connection.targetNodeId === currentId) delete state.connectionsById[id]; } for (const connection of Object.values(state.secondaryConnectionsById)) if (nodeIds.includes(connection.sourceNodeId) || nodeIds.includes(connection.targetNodeId)) delete state.secondaryConnectionsById[connection.connectionId]; const parentPort = state.portsById[rootParentPortId]; if (parentPort) parentPort.occupiedByNodeId = null; publish(detachBranch ? ASSEMBLY_EVENTS.BRANCH_DETACHED : ASSEMBLY_EVENTS.MODULE_DETACHED, { nodeIds }); return nodeIds; }
  const api = { getSnapshot, requireNode, publishDamageChange, publish, mountModule, moveNode, addSecondaryConnection, detachNode };
  return api;
}
