import { ASSEMBLY_EVENTS } from "../assembly-events.js";
import { assertAssemblyInvariants, getBranchNodeIds, getChildren, wouldCreateCycle } from "./assembly-graph.js";
import { createAssemblySnapshot } from "./assembly-snapshot.js";

export function createAssemblyService({ state, eventBus, idFactory, runInventory } = {}) {
  const getSnapshot = () => createAssemblySnapshot(state);
  const requireNode = nodeId => { const node = state.nodesById[nodeId]; if (!node) throw new Error(`Unknown assembly node: ${nodeId}`); return node; };
  const publish = (eventName, payload, { structural = true, visual = true } = {}) => { if (structural) state.structuralRevision += 1; if (visual) state.visualRevision += 1; assertAssemblyInvariants(state); if (eventName !== ASSEMBLY_EVENTS.CHANGED) eventBus?.emit(eventName, payload); eventBus?.emit(ASSEMBLY_EVENTS.CHANGED, getSnapshot()); };
  const publishDamageChange = nodeId => publish(ASSEMBLY_EVENTS.DAMAGE_CHANGED, { nodeId }, { structural: false, visual: true });
  const transaction=operation=>{const previous=structuredClone(state);try{return operation();}catch(error){for(const key of Object.keys(state))delete state[key];Object.assign(state,previous);throw error;}};
  const rebaseBranchDepth=(nodeId,branchDepth)=>{const node=requireNode(nodeId);for(const portId of node.childPortIds??[]){const port=state.portsById[portId];if(!port)continue;state.portsById[portId]={...port,branchDepth};if(port.occupiedByNodeId)rebaseBranchDepth(port.occupiedByNodeId,branchDepth+1);}};

  function mountModule({ moduleInstanceId, definitionId, parentPort, assemblyProfile, transform }) { if (Object.values(state.nodesById).some(node => node.moduleInstanceId === moduleInstanceId)) throw new Error(`Module already mounted: ${moduleInstanceId}`); if (!parentPort || parentPort.occupiedByNodeId) throw new Error("Mount port is unavailable"); const nodeId = idFactory.create("assembly-node"); const node = { nodeId, parentNodeId: parentPort.parentNodeId, parentPortId: parentPort.portId, moduleInstanceId, definitionId, visualProfileId: assemblyProfile.visualProfileId, variantSeed: assemblyProfile.variantSeed, sizeClass: assemblyProfile.sizeClass, mountType: parentPort.mountType, mass: assemblyProfile.mass, localPosition: transform.position, localRotation: transform.rotation, armorIntegrity: assemblyProfile.damage.armor, maxArmorIntegrity: assemblyProfile.damage.armor, coreIntegrity: assemblyProfile.damage.core, maxCoreIntegrity: assemblyProfile.damage.core, damageState: "intact", childPortIds: [] }; state.nodesById[nodeId] = node; if (!state.nodeIdByModuleInstanceId) state.nodeIdByModuleInstanceId = {}; if (moduleInstanceId) state.nodeIdByModuleInstanceId[moduleInstanceId] = nodeId; state.portsById[parentPort.portId] = { ...parentPort, occupiedByNodeId: nodeId }; const connectionId = idFactory.create("assembly-connection"); state.connectionsById[connectionId] = { connectionId, sourceNodeId: parentPort.parentNodeId, targetNodeId: nodeId, sourcePortId: parentPort.portId, structuralStrength: parentPort.loadCapacity, energyThroughput: parentPort.energyClass, visualConnectorType: parentPort.mountType }; for (const template of assemblyProfile.childPorts ?? []) { const portId = idFactory.create("assembly-port"); state.portsById[portId] = { ...template, portId, parentNodeId: nodeId, branchDepth: (parentPort.branchDepth ?? 0) + 1, occupiedByNodeId: null }; node.childPortIds.push(portId); } publish(ASSEMBLY_EVENTS.MODULE_MOUNTED, { nodeId, moduleInstanceId }); return nodeId; }
  function moveNode({ nodeId, targetPort, transform }) { const node = requireNode(nodeId); if (nodeId === state.rootNodeId) throw new Error("Node cannot be moved"); if (!targetPort || targetPort.occupiedByNodeId) throw new Error("Target port is unavailable"); if (wouldCreateCycle(state, nodeId, targetPort.parentNodeId)) throw new Error("Move would create a cycle"); const oldPort = state.portsById[node.parentPortId]; if (oldPort) state.portsById[oldPort.portId] = { ...oldPort, occupiedByNodeId: null }; state.portsById[targetPort.portId] = { ...targetPort, occupiedByNodeId: nodeId }; Object.assign(node, { parentNodeId: targetPort.parentNodeId, parentPortId: targetPort.portId, localPosition: transform.position, localRotation: transform.rotation }); rebaseBranchDepth(nodeId,(targetPort.branchDepth??0)+1);const connection = Object.values(state.connectionsById).find(item => item.targetNodeId === nodeId); if (connection) Object.assign(connection, { sourceNodeId: targetPort.parentNodeId, sourcePortId: targetPort.portId }); publish(ASSEMBLY_EVENTS.MODULE_MOVED, { nodeId, targetPortId: targetPort.portId }); return nodeId; }
  function addSecondaryConnection({ sourceNodeId, targetNodeId, profile }) { requireNode(sourceNodeId); requireNode(targetNodeId); const connectionId = idFactory.create("assembly-bridge"); state.secondaryConnectionsById[connectionId] = { connectionId, sourceNodeId, targetNodeId, structuralStrength: profile.structuralStrength, energyThroughput: profile.energyThroughput, visualConnectorType: profile.visualConnectorType }; publish(ASSEMBLY_EVENTS.CHANGED, { connectionId }); return connectionId; }
  function rotateNode({nodeId,localRotation}){const node=requireNode(nodeId);if(nodeId===state.rootNodeId)throw new Error("Root rotation is controlled by the ship frame");state.nodesById[nodeId]={...node,localRotation};publish(ASSEMBLY_EVENTS.MODULE_MOVED,{nodeId,localRotation});return nodeId;}
  function moveBranch({rootNodeId,targetPort,transform}){const branchIds=getBranchNodeIds(state,rootNodeId);if(branchIds.includes(targetPort.parentNodeId))throw new Error("Branch move would create a cycle");moveNode({nodeId:rootNodeId,targetPort,transform});return branchIds;}
  function promoteSecondaryConnection(nodeId,connectionId){const node=requireNode(nodeId),bridge=state.secondaryConnectionsById[connectionId];if(!bridge)throw new Error(`Unknown secondary connection: ${connectionId}`);const newParentNodeId=bridge.sourceNodeId===nodeId?bridge.targetNodeId:bridge.sourceNodeId,oldPort=state.portsById[node.parentPortId];if(oldPort)state.portsById[oldPort.portId]={...oldPort,occupiedByNodeId:null};for(const[id,connection]of Object.entries(state.connectionsById))if(connection.targetNodeId===nodeId)delete state.connectionsById[id];state.nodesById[nodeId]={...node,parentNodeId:newParentNodeId,parentPortId:null,supportMode:"secondary-support"};state.connectionsById[connectionId]={...bridge,sourceNodeId:newParentNodeId,targetNodeId:nodeId,sourcePortId:null};delete state.secondaryConnectionsById[connectionId];publish(ASSEMBLY_EVENTS.CHANGED,{nodeId,connectionId,mode:"promoted-secondary"});}
  function createEmergencyBrace(nodeId){const node=requireNode(nodeId),oldPort=state.portsById[node.parentPortId];if(oldPort)state.portsById[oldPort.portId]={...oldPort,occupiedByNodeId:null};for(const[id,connection]of Object.entries(state.connectionsById))if(connection.targetNodeId===nodeId)delete state.connectionsById[id];state.nodesById[nodeId]={...node,parentNodeId:state.rootNodeId,parentPortId:null,supportMode:"emergency-brace"};const connectionId=idFactory.create("emergency-brace");state.connectionsById[connectionId]={connectionId,sourceNodeId:state.rootNodeId,targetNodeId:nodeId,sourcePortId:null,structuralStrength:2,energyThroughput:"emergency",visualConnectorType:"brace"};publish(ASSEMBLY_EVENTS.CHANGED,{nodeId,mode:"emergency-brace"});}
  function applyBranchPenalty(nodeId,penaltyId){const branchIds=getBranchNodeIds(state,nodeId);for(const id of branchIds){const node=requireNode(id);state.nodesById[id]={...node,structuralPenalties:[...new Set([...(node.structuralPenalties??[]),penaltyId])]};}publish(ASSEMBLY_EVENTS.CHANGED,{nodeId,branchIds,penaltyId});}
  function detachNode({ nodeId, detachBranch = false, skipInventoryStore = false }) { if (nodeId === state.rootNodeId) throw new Error("Root node cannot be detached"); if (!detachBranch && getChildren(state, nodeId).length) throw new Error("Node has dependent children"); const rootParentPortId = requireNode(nodeId).parentPortId; const nodeIds = detachBranch ? getBranchNodeIds(state, nodeId) : [nodeId]; const detachedSet = new Set(nodeIds); for (const currentId of [...nodeIds].reverse()) { const node = requireNode(currentId); state.detachedItems.push({ moduleInstanceId: node.moduleInstanceId, definitionId: node.definitionId, formerNodeId: currentId, damageState: "detached" }); if(!skipInventoryStore){const item=runInventory?.store(node.moduleInstanceId);if(item)item.damageState="detached";} for (const portId of node.childPortIds ?? []) delete state.portsById[portId]; delete state.nodesById[currentId]; if (state.nodeIdByModuleInstanceId && node.moduleInstanceId) delete state.nodeIdByModuleInstanceId[node.moduleInstanceId]; } for (const [id, connection] of Object.entries(state.connectionsById)) if (detachedSet.has(connection.sourceNodeId) || detachedSet.has(connection.targetNodeId)) delete state.connectionsById[id]; for (const connection of Object.values(state.secondaryConnectionsById)) if (detachedSet.has(connection.sourceNodeId) || detachedSet.has(connection.targetNodeId)) delete state.secondaryConnectionsById[connection.connectionId]; const parentPort = state.portsById[rootParentPortId]; if (parentPort) parentPort.occupiedByNodeId = null; publish(detachBranch ? ASSEMBLY_EVENTS.BRANCH_DETACHED : ASSEMBLY_EVENTS.MODULE_DETACHED, { nodeIds }); return nodeIds; }
  function dismantleNode({nodeId,includeBranch=false}){const nodeIds=includeBranch?getBranchNodeIds(state,nodeId):[nodeId],items=nodeIds.map(currentId=>requireNode(currentId).moduleInstanceId).filter(Boolean),detached=detachNode({nodeId,detachBranch:includeBranch,skipInventoryStore:true});for(const itemInstanceId of items){const item=runInventory?.store(itemInstanceId);if(item)item.damageState="intact";}return detached;}
  function replacePort({portId,profile={}}){const port=state.portsById[portId];if(!port)throw new Error(`Unknown assembly port: ${portId}`);state.portsById[portId]={...port,...profile,portId,parentNodeId:port.parentNodeId,occupiedByNodeId:port.occupiedByNodeId,damageState:"intact"};publish(ASSEMBLY_EVENTS.CHANGED,{portId,mode:"port-replaced"});return state.portsById[portId];}
  const api = { getSnapshot, requireNode, publishDamageChange, publish, transaction, mountModule:args=>transaction(()=>mountModule(args)), moveNode:args=>transaction(()=>moveNode(args)), moveBranch:args=>transaction(()=>moveBranch(args)), rotateNode:args=>transaction(()=>rotateNode(args)), dismantleNode:args=>transaction(()=>dismantleNode(args)), addSecondaryConnection:args=>transaction(()=>addSecondaryConnection(args)), promoteSecondaryConnection:(...args)=>transaction(()=>promoteSecondaryConnection(...args)), createEmergencyBrace:args=>transaction(()=>createEmergencyBrace(args)), applyBranchPenalty:(...args)=>transaction(()=>applyBranchPenalty(...args)), replacePort:args=>transaction(()=>replacePort(args)), detachNode:args=>transaction(()=>detachNode(args)) };
  return api;
}
